version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "Manager_Alumni"
      MYSQL_USER: "Nonobeam"
      MYSQL_PASSWORD: "Haha123456"
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev_phpmyadmin"
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
